name: build

on: [push, pull_request]

jobs:
  build_win:
    name: Build on Windows
    runs-on: windows-2022

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip install git+https://github.com/lmdu/AutoDockTools_py3
          pip install https://github.com/lmdu/pymol-wheel/releases/download/2.6.0.post4/pymol-2.6.0a0-cp310-cp310-win_amd64.whl
          pip install https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1.post8/openbabel-3.1.1-cp310-cp310-win_amd64.whl
          pip install https://github.com/lmdu/openmm-wheel/releases/download/8.0.0.post1/OpenMM-8.0.0-cp310-cp310-win_amd64.whl
          pip install https://github.com/openmm/pdbfixer/archive/refs/tags/1.9.tar.gz
          pip install -r src/requirements.txt
          python package\slim_meeko.py

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        run: |
          $line = Select-String -Path src\config.py -Pattern 'DOCKEY_VERSION =' | Out-String
          $version = $line.Split('"')[1]
          iscc /DMyAppVersion=$version package/build_win_installer.iss
          cd dist
          7z a Dockey-v$version-win64.7z Dockey

      - uses: actions/upload-artifact@v7
        with:
          name: Dockey-win64
          path: |
            dist/*.exe
            dist/*.7z

      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.exe
            dist/*.7z

  build_modern:
    name: Build on Ubuntu22.04
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install build requirements
        run: |
          pip3 install git+https://github.com/lmdu/AutoDockTools_py3
          pip3 install https://github.com/lmdu/pymol-wheel/releases/download/2.6.0.post4/pymol-2.6.0a0-cp310-cp310-manylinux_2_28_x86_64.whl
          pip3 install https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1.post9/openbabel-3.1.1-cp310-cp310-manylinux_2_28_x86_64.whl
          pip3 install https://github.com/lmdu/openmm-wheel/releases/download/8.0.0.post1/OpenMM-8.0.0-cp310-cp310-manylinux_2_28_x86_64.whl
          pip3 install https://github.com/openmm/pdbfixer/archive/refs/tags/1.9.tar.gz
          pip3 install -r src/requirements.txt
          python3 package/slim_meeko.py

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package installer
        run: |
          version=`awk '/^DOCKEY_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          chmod a+x package/build_linux_desktop.sh
          package/build_linux_desktop.sh $version

      - uses: actions/upload-artifact@v7
        with:
          name: Dockey-ubuntu22.04
          path: |
            dist/*.AppImage

      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.AppImage

  build_mac:
    name: Build on MacOS
    runs-on: macos-15-intel

    steps:
      - uses: actions/checkout@v6

      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install requirements
        run: |
          pip3 install git+https://github.com/lmdu/AutoDockTools_py3
          pip3 install https://github.com/lmdu/pymol-wheel/releases/download/2.6.0.post4/pymol-2.6.0a0-cp310-cp310-macosx_10_9_x86_64.whl
          pip3 install https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1.post8/openbabel-3.1.1-cp310-cp310-macosx_11_0_x86_64.whl
          pip3 install https://github.com/lmdu/openmm-wheel/releases/download/8.0.0.post1/OpenMM-8.0.0-cp310-cp310-macosx_10_9_x86_64.whl
          pip3 install https://github.com/openmm/pdbfixer/archive/refs/tags/1.9.tar.gz
          pip3 install -r src/requirements.txt
          python3 package/slim_meeko.py

      - name: Build executable
        run: pyinstaller package/build.spec

      - name: Package
        run: |
          version=`awk '/^DOCKEY_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          chmod a+x package/build_mac_installer.sh
          package/build_mac_installer.sh $version x64

      - uses: actions/upload-artifact@v7
        with:
          name: Dockey-macos
          path: |
            dist/*.dmg

      - uses: softprops/action-gh-release@v3
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            dist/*.dmg
