name: build

on: [push, pull_request]

jobs:
  build_win:
    name: Build on Windows
    runs-on: windows-2019

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          wsl wget https://github.com/lmdu/pymol-wheel/releases/download/2.6.0a0/pymol-2.6.0a0-cp38-cp38-win_amd64.whl
          wsl wget https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1/openbabel-3.1.1-cp38-cp38-win_amd64.whl
          pip install pymol-2.6.0a0-cp38-cp38-win_amd64.whl
          pip install openbabel-3.1.1-cp38-cp38-win_amd64.whl
          pip install psutil==5.9.0
          pip install apsw-wheels==3.36.0.post1
          pip install PySide6==6.2.2.1
          pip install pyinstaller==4.7

      - name: Build executable
        run: pyinstaller package/build_win.spec

      - name: Package
        run: |
          $lines = Get-Content src/config.py
          $version = $lines[9].Split('"')[1]
          iscc /DMyAppVersion=$version package/build_win_installer.iss

      - uses: actions/upload-artifact@v2
        with:
          name: Dockey-win64.exe
          path: dist/*.exe

  build_linux:
    name: Build on Linux
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          wget https://github.com/lmdu/pymol-wheel/releases/download/2.6.0a0/pymol-2.6.0a0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          wget https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1/openbabel-3.1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install pymol-2.6.0a0-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install openbabel-3.1.1.1-cp38-cp38-manylinux_2_17_x86_64.manylinux2014_x86_64.whl
          pip install psutil==5.9.0
          pip install apsw-wheels==3.36.0.post1
          pip install PySide6==6.2.2.1
          pip install pyinstaller==4.7

      - name: Build executable
        run: pyinstaller package/build_linux.spec

      - name: Package installer
        run: |
          version=`awk '/^DOCKEY_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          cd dist
          tar -czvf Dockey-v${version}-linux.tar.gz Dockey
          chmod a+x ../package/build_linux_desktop.sh
          ../package/build_linux_desktop.sh $version

      - uses: actions/upload-artifact@v2
        with:
          name: Dockey-amd64.deb
          path: dist/*.deb

      - uses: actions/upload-artifact@v2
        with:
          name: Dockey-amd64.rpm
          path: dist/*.rpm

      - uses: actions/upload-artifact@v2
        with:
          name: Dockey-amd64.tar.gz
          path: dist/*.tar.gz

  build_mac:
    name: Build on Mac
    runs-on: macos-10.15

    steps:
      - uses: actions/checkout@v2

      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install requirements
        run: |
          wget https://github.com/lmdu/pymol-wheel/releases/download/2.6.0a0/pymol-2.6.0a0-cp38-cp38-macosx_10_9_x86_64.whl
          wget https://github.com/lmdu/openbabel-wheel/releases/download/3.1.1/openbabel-3.1.1.1-cp38-cp38-macosx_10_9_x86_64.whl
          pip install pymol-2.6.0a0-cp38-cp38-macosx_10_9_x86_64.whl
          pip install openbabel-3.1.1.1-cp38-cp38-macosx_10_9_x86_64.whl
          pip install psutil==5.9.0
          pip install apsw-wheels==3.36.0.post1
          pip install PySide6==6.2.2.1
          pip install pyinstaller==4.7

      - name: Build executable
        run: pyinstaller package/build_mac.spec

      - name: Package
        run: |
          version=`awk '/^DOCKEY_VERSION/{print $NF}' src/config.py | sed 's/\"//g'`
          cd dist
          sudo npm install --global create-dmg
          create-dmg Dockey.app
          mv "Dockey 0.0.0.dmg" Dockey-v${version}-macos.dmg

      - uses: actions/upload-artifact@v2
        with:
          name: Dockey-macos.dmg
          path: dist/*.dmg


